### ISSUE TITLE
🤔 Kubernetes Operator v2 deployment question

### ISSUE THREAD

**Issue by itayporezky** [hashicorp/hcp-terraform-operator#499]
### Operator Version, Kind and Kubernetes Version
 - Operator version: N/A
 - Kind: N/A
 - Kubernetes version: N/A

### Question

I'm looking at the [Kubernetes Operator v2](https://developer.hashicorp.com/terraform/tutorials/kubernetes/kubernetes-operator-v2) guide, i don't understand why `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` credentials are required, can you please let me know?

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by appilon** [comment]
The guide just happens to use AWS for its examples therefore requiring the key and secret.
