### ISSUE TITLE
🤔 why is the latest release here 2.7 but the latest on dockerhub 2.5?

### ISSUE THREAD

**Issue by tkellen** [hashicorp/hcp-terraform-operator#524]
### Operator Version, Kind and Kubernetes Version
 - Operator version: n/a
 - Kind: n/a
 - Kubernetes version: n/a

### YAML Manifest File

```yaml
# Copy-paste your YAML manifest here
```

### Question
See the topic.

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by appilon** [comment]
I'm not sure where you see 2.5 as the latest but this is the [official image](https://hub.docker.com/layers/hashicorp/hcp-terraform-operator/2.7/images/sha256-2abf40dafd248ea1c73e7ed276aacf7ff43b5e4f8966177c193978f7096d0238?context=explore) v2.7
